services:
  - name: ratecard-backend
    type: web
    env: python
    rootDir: backend
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port 10000

    envVars:
      - key: GOOGLE_CREDENTIALS_FILE
        value: /etc/secrets/GOOGLE_CREDENTIALS_FILE
      - key: BQ_PROJECT
        value: adex-5555
      - key: BQ_DATASET
        value: RATECARD
      - key: ENV
        value: production

    secretFiles:
      - name: GOOGLE_CREDENTIALS_FILE
        mountPath: /etc/secrets/GOOGLE_CREDENTIALS_FILE
